[tool.black]
line-length = 88
target-version = ['py35', 'py36', 'py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | \.benchmarks
    | docs_src/rtd
    | docs_src/rtd_output
    | docs_src/splash
    | docs
    | build
    | dist
  )/
)
'''
